"""
SuperBrain LAN Sync Server

Production-quality asyncio WebSocket server for peer-to-peer knowledge chunk
synchronization over LAN. Part of the SuperBrain decentralized AI knowledge
network on Bittensor.

Protocol overview:
    1. Peers discover each other via mDNS (_superbrain._tcp.local.)
    2. Connecting peer sends HANDSHAKE with node_id and chunk_count
    3. Either side may send SYNC_REQUEST with a manifest of known chunk hashes
    4. Responder computes delta and replies with SYNC_RESPONSE containing only
       chunks the requester does not already have
    5. Received chunks are verified (Ed25519 signature), then ingested into
       Qdrant with embeddings generated by Ollama nomic-embed-text
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import signal
import socket
import time
import threading
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set

import httpx
import websockets
from websockets.asyncio.server import Server as WSServer, ServerConnection
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    PublicFormat,
)
from zeroconf import ServiceBrowser, ServiceInfo, ServiceListener, Zeroconf

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_HOST: str = "0.0.0.0"
DEFAULT_PORT: int = 8765
PROTOCOL_VERSION: str = "1.0"
PING_INTERVAL_S: int = 30
PING_TIMEOUT_S: int = 10

QDRANT_URL: str = "http://localhost:6333"
QDRANT_COLLECTION: str = "sb_docs_v1_ollama"
OLLAMA_URL: str = "http://localhost:11434"
EMBEDDING_MODEL: str = "nomic-embed-text"

MDNS_SERVICE_TYPE: str = "_superbrain._tcp.local."

VALID_MESSAGE_TYPES: Set[str] = {"handshake", "sync_request", "sync_response", "error"}

logger = logging.getLogger("superbrain.lan_sync")


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class Chunk:
    """A single knowledge chunk with its metadata and cryptographic proof."""

    hash: str
    content: str
    contributor_id: str
    timestamp: int
    visibility: str
    signature: str
    layer: str = "lan"

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the chunk to a JSON-safe dictionary."""
        return {
            "hash": self.hash,
            "content": self.content,
            "contributor_id": self.contributor_id,
            "timestamp": self.timestamp,
            "visibility": self.visibility,
            "signature": self.signature,
            "layer": self.layer,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Chunk:
        """Deserialize a chunk from a dictionary.

        Raises:
            KeyError: If required fields are missing.
            TypeError: If field types are wrong.
        """
        return cls(
            hash=str(data["hash"]),
            content=str(data["content"]),
            contributor_id=str(data["contributor_id"]),
            timestamp=int(data["timestamp"]),
            visibility=str(data["visibility"]),
            signature=str(data["signature"]),
            layer=str(data.get("layer", "lan")),
        )


@dataclass
class PeerInfo:
    """Metadata about a connected peer."""

    node_id: str
    version: str
    chunk_count: int
    connected_at: float = field(default_factory=time.time)
    last_seen: float = field(default_factory=time.time)


# ---------------------------------------------------------------------------
# ChunkStore — thread-safe in-memory chunk storage
# ---------------------------------------------------------------------------


class ChunkStore:
    """Thread-safe in-memory store for knowledge chunks.

    Provides O(1) lookup by hash and safe concurrent access from both the
    asyncio event loop and any background threads (e.g. mDNS callbacks).
    """

    def __init__(self) -> None:
        self._lock: threading.Lock = threading.Lock()
        self._chunks: Dict[str, Chunk] = {}

    def has(self, chunk_hash: str) -> bool:
        """Check whether a chunk with the given hash exists."""
        with self._lock:
            return chunk_hash in self._chunks

    def get(self, chunk_hash: str) -> Optional[Chunk]:
        """Return a chunk by hash, or ``None`` if not found."""
        with self._lock:
            return self._chunks.get(chunk_hash)

    def put(self, chunk: Chunk) -> bool:
        """Store a chunk. Returns ``True`` if it was new, ``False`` if duplicate."""
        with self._lock:
            if chunk.hash in self._chunks:
                return False
            self._chunks[chunk.hash] = chunk
            return True

    def hashes(self) -> List[str]:
        """Return a snapshot of all stored chunk hashes."""
        with self._lock:
            return list(self._chunks.keys())

    def count(self) -> int:
        """Return the number of stored chunks."""
        with self._lock:
            return len(self._chunks)

    def get_delta(self, remote_manifest: Set[str]) -> List[Chunk]:
        """Return chunks that are in this store but NOT in *remote_manifest*."""
        with self._lock:
            local_hashes = set(self._chunks.keys())
            missing = local_hashes - remote_manifest
            return [self._chunks[h] for h in missing]


# ---------------------------------------------------------------------------
# mDNS peer listener
# ---------------------------------------------------------------------------


class _PeerListener(ServiceListener):
    """Zeroconf listener that tracks discovered SuperBrain peers."""

    def __init__(self, own_node_id: str) -> None:
        self.own_node_id = own_node_id
        self.peers: Dict[str, ServiceInfo] = {}
        self._lock = threading.Lock()

    def update_service(self, zc: Zeroconf, type_: str, name: str) -> None:
        """Handle a service update."""
        info = zc.get_service_info(type_, name)
        if info is not None:
            node_id = info.properties.get(b"node_id", b"").decode()
            if node_id and node_id != self.own_node_id:
                with self._lock:
                    self.peers[node_id] = info
                logger.debug("Peer updated: %s", node_id[:16])

    def remove_service(self, zc: Zeroconf, type_: str, name: str) -> None:
        """Handle a service removal."""
        with self._lock:
            to_remove = [
                nid
                for nid, si in self.peers.items()
                if si.name == name
            ]
            for nid in to_remove:
                del self.peers[nid]
                logger.info("Peer removed: %s", nid[:16])

    def add_service(self, zc: Zeroconf, type_: str, name: str) -> None:
        """Handle a newly discovered service."""
        info = zc.get_service_info(type_, name)
        if info is not None:
            node_id = info.properties.get(b"node_id", b"").decode()
            if node_id and node_id != self.own_node_id:
                with self._lock:
                    self.peers[node_id] = info
                logger.info("Peer discovered: %s", node_id[:16])

    def get_peers(self) -> Dict[str, ServiceInfo]:
        """Return a snapshot of known peers."""
        with self._lock:
            return dict(self.peers)


# ---------------------------------------------------------------------------
# LANSyncServer
# ---------------------------------------------------------------------------


class LANSyncServer:
    """Asyncio WebSocket server for LAN-based knowledge chunk synchronization.

    Parameters:
        host:        Bind address (default ``0.0.0.0``).
        port:        Bind port (default ``8765``).
        node_id:     SHA-256 hex digest of this node's public key.
        private_key: Ed25519 private key for signing outgoing chunks.
        chunk_store: Shared :class:`ChunkStore` instance.
    """

    def __init__(
        self,
        host: str = DEFAULT_HOST,
        port: int = DEFAULT_PORT,
        node_id: str = "",
        private_key: Optional[Ed25519PrivateKey] = None,
        chunk_store: Optional[ChunkStore] = None,
    ) -> None:
        self.host: str = host
        self.port: int = port
        self.node_id: str = node_id
        self.private_key: Optional[Ed25519PrivateKey] = private_key
        self.public_key: Optional[Ed25519PublicKey] = (
            private_key.public_key() if private_key else None
        )
        self.chunk_store: ChunkStore = chunk_store or ChunkStore()

        # Connected peers keyed by websocket id
        self._peers: Dict[int, PeerInfo] = {}
        self._server: Optional[WSServer] = None
        self._running: bool = False

        # mDNS / Zeroconf
        self._zeroconf: Optional[Zeroconf] = None
        self._mdns_info: Optional[ServiceInfo] = None
        self._peer_listener: Optional[_PeerListener] = None
        self._browser: Optional[ServiceBrowser] = None

        # HTTP client for Qdrant / Ollama — created lazily in the event loop
        self._http_client: Optional[httpx.AsyncClient] = None

    # -----------------------------------------------------------------
    # Lifecycle
    # -----------------------------------------------------------------

    async def start(self) -> None:
        """Start the WebSocket server and mDNS registration.

        This coroutine runs until :meth:`stop` is called or a signal is
        received.
        """
        logger.info(
            "Starting LAN sync server on %s:%d  node=%s",
            self.host,
            self.port,
            self.node_id[:16] if self.node_id else "<no-id>",
        )

        self._http_client = httpx.AsyncClient(timeout=30.0)
        self._running = True

        self.register_mdns()

        self._server = await websockets.asyncio.server.serve(
            self.handle_connection,
            self.host,
            self.port,
            ping_interval=PING_INTERVAL_S,
            ping_timeout=PING_TIMEOUT_S,
        )

        logger.info("LAN sync server listening on ws://%s:%d", self.host, self.port)

        # Block until the server is closed
        await self._server.wait_closed()

    async def stop(self) -> None:
        """Gracefully shut down the server, mDNS, and HTTP client."""
        logger.info("Shutting down LAN sync server ...")
        self._running = False

        if self._server is not None:
            self._server.close()
            await self._server.wait_closed()
            logger.debug("WebSocket server closed.")

        self.unregister_mdns()

        if self._http_client is not None:
            await self._http_client.aclose()
            self._http_client = None

        logger.info("LAN sync server stopped.")

    # -----------------------------------------------------------------
    # WebSocket connection handler
    # -----------------------------------------------------------------

    async def handle_connection(self, websocket: ServerConnection) -> None:
        """Handle the full lifecycle of a single WebSocket connection.

        The first message MUST be a ``handshake``; subsequent messages are
        dispatched by type.
        """
        remote = websocket.remote_address
        conn_id = id(websocket)
        logger.info("New connection from %s", remote)

        try:
            # --- Expect handshake first --------------------------------
            try:
                raw = await asyncio.wait_for(websocket.recv(), timeout=10.0)
            except asyncio.TimeoutError:
                await self._send_error(websocket, "HANDSHAKE_TIMEOUT", "No handshake received within 10 s")
                return

            message = self._parse_message(raw)
            if message is None:
                await self._send_error(websocket, "INVALID_JSON", "Failed to parse JSON message")
                return

            if message.get("type") != "handshake":
                await self._send_error(websocket, "HANDSHAKE_REQUIRED", "First message must be a handshake")
                return

            if not await self.handle_handshake(websocket, message):
                return  # handshake handler already sent an error

            # --- Main message loop -------------------------------------
            async for raw in websocket:
                if not self._running:
                    break

                message = self._parse_message(raw)
                if message is None:
                    await self._send_error(websocket, "INVALID_JSON", "Failed to parse JSON message")
                    continue

                msg_type = message.get("type")

                if msg_type == "sync_request":
                    await self.handle_sync_request(websocket, message)
                elif msg_type == "sync_response":
                    await self._handle_sync_response(websocket, message)
                elif msg_type == "error":
                    logger.warning(
                        "Peer %s sent error: [%s] %s",
                        remote,
                        message.get("code", "?"),
                        message.get("message", "?"),
                    )
                else:
                    await self._send_error(
                        websocket,
                        "UNKNOWN_TYPE",
                        f"Unknown message type: {msg_type}",
                    )

        except websockets.exceptions.ConnectionClosed as exc:
            logger.info("Connection from %s closed: %s", remote, exc)
        except Exception:
            logger.exception("Unhandled error on connection from %s", remote)
        finally:
            self._peers.pop(conn_id, None)
            logger.info("Connection from %s cleaned up.", remote)

    # -----------------------------------------------------------------
    # Handshake
    # -----------------------------------------------------------------

    async def handle_handshake(
        self, websocket: ServerConnection, message: Dict[str, Any]
    ) -> bool:
        """Validate an incoming handshake and register the peer.

        Returns ``True`` if the handshake succeeded, ``False`` otherwise.
        """
        node_id = message.get("node_id")
        version = message.get("version")
        chunk_count = message.get("chunk_count")
        timestamp = message.get("timestamp")

        # --- Validation ------------------------------------------------
        if not node_id or not isinstance(node_id, str) or len(node_id) != 64:
            await self._send_error(
                websocket, "INVALID_HANDSHAKE", "node_id must be a 64-char hex SHA-256 digest"
            )
            return False

        if version != PROTOCOL_VERSION:
            await self._send_error(
                websocket,
                "VERSION_MISMATCH",
                f"Unsupported protocol version: {version} (expected {PROTOCOL_VERSION})",
            )
            return False

        if not isinstance(chunk_count, int) or chunk_count < 0:
            await self._send_error(
                websocket, "INVALID_HANDSHAKE", "chunk_count must be a non-negative integer"
            )
            return False

        if not isinstance(timestamp, (int, float)):
            await self._send_error(
                websocket, "INVALID_HANDSHAKE", "timestamp must be a number"
            )
            return False

        # --- Register peer ---------------------------------------------
        peer = PeerInfo(
            node_id=node_id,
            version=version,
            chunk_count=chunk_count,
        )
        self._peers[id(websocket)] = peer

        logger.info(
            "Handshake OK: node=%s  chunks=%d  version=%s",
            node_id[:16],
            chunk_count,
            version,
        )

        # --- Send our handshake back -----------------------------------
        response: Dict[str, Any] = {
            "type": "handshake",
            "node_id": self.node_id,
            "version": PROTOCOL_VERSION,
            "chunk_count": self.chunk_store.count(),
            "timestamp": int(time.time()),
        }
        await websocket.send(json.dumps(response))
        return True

    # -----------------------------------------------------------------
    # Sync request handling (we are the SENDER)
    # -----------------------------------------------------------------

    async def handle_sync_request(
        self, websocket: ServerConnection, message: Dict[str, Any]
    ) -> None:
        """Respond to a SYNC_REQUEST with the delta of chunks the peer lacks.

        The peer provides a manifest of hashes it already owns.  We compute
        which of our chunks are missing from that manifest and send them.
        """
        manifest_raw = message.get("manifest")
        if not isinstance(manifest_raw, list):
            await self._send_error(websocket, "INVALID_REQUEST", "manifest must be a list of hash strings")
            return

        remote_manifest: Set[str] = set(manifest_raw)
        delta_chunks: List[Chunk] = self.chunk_store.get_delta(remote_manifest)
        deduplicated = self.chunk_store.count() - len(delta_chunks)

        response: Dict[str, Any] = {
            "type": "sync_response",
            "chunks": [c.to_dict() for c in delta_chunks],
            "sent": len(delta_chunks),
            "deduplicated": deduplicated,
        }

        await websocket.send(json.dumps(response))
        logger.info(
            "Sync response: sent=%d  deduplicated=%d",
            len(delta_chunks),
            deduplicated,
        )

    # -----------------------------------------------------------------
    # Sync response handling (we are the RECEIVER)
    # -----------------------------------------------------------------

    async def _handle_sync_response(
        self, websocket: ServerConnection, message: Dict[str, Any]
    ) -> None:
        """Process an incoming SYNC_RESPONSE — verify and ingest new chunks."""
        raw_chunks = message.get("chunks")
        if not isinstance(raw_chunks, list):
            await self._send_error(websocket, "INVALID_RESPONSE", "chunks must be a list")
            return

        accepted = 0
        rejected = 0
        duplicates = 0

        for raw in raw_chunks:
            try:
                chunk = Chunk.from_dict(raw)
            except (KeyError, TypeError, ValueError) as exc:
                logger.warning("Malformed chunk in sync_response: %s", exc)
                rejected += 1
                continue

            # Verify content hash
            computed_hash = hashlib.sha256(chunk.content.encode("utf-8")).hexdigest()
            if computed_hash != chunk.hash:
                logger.warning(
                    "Chunk hash mismatch: expected=%s  computed=%s",
                    chunk.hash[:16],
                    computed_hash[:16],
                )
                rejected += 1
                continue

            # Verify Ed25519 signature
            if not self.verify_chunk_signature(chunk):
                logger.warning("Signature verification failed for chunk %s", chunk.hash[:16])
                rejected += 1
                continue

            # Deduplicate locally
            if self.chunk_store.has(chunk.hash):
                duplicates += 1
                continue

            # Ingest into Qdrant and local store
            if await self.ingest_chunk(chunk):
                accepted += 1
            else:
                rejected += 1

        logger.info(
            "Sync ingest complete: accepted=%d  rejected=%d  duplicates=%d",
            accepted,
            rejected,
            duplicates,
        )

    # -----------------------------------------------------------------
    # Signature verification
    # -----------------------------------------------------------------

    def verify_chunk_signature(self, chunk: Chunk) -> bool:
        """Verify the Ed25519 signature on a chunk.

        The signed message is the concatenation of:
            chunk.hash (hex str -> bytes) +
            chunk.contributor_id (hex str -> bytes) +
            str(chunk.timestamp) (str -> bytes) +
            chunk.visibility (str -> bytes)

        The public key is derived from the contributor_id. In a full
        deployment the public key would be fetched from a key registry;
        here we attempt to reconstruct it from local knowledge or skip
        verification for chunks we ourselves signed.

        Returns:
            ``True`` if valid, ``False`` otherwise.
        """
        try:
            sig_bytes = bytes.fromhex(chunk.signature)
            message_bytes = (
                chunk.hash.encode("utf-8")
                + chunk.contributor_id.encode("utf-8")
                + str(chunk.timestamp).encode("utf-8")
                + chunk.visibility.encode("utf-8")
            )

            # If the chunk is from ourselves, use our own public key
            if chunk.contributor_id == self.node_id and self.public_key is not None:
                self.public_key.verify(sig_bytes, message_bytes)
                return True

            # For foreign chunks the caller is expected to supply the public
            # key via a key registry.  For now we log and accept if we cannot
            # locate the key (this keeps the server functional during early
            # development while still logging the gap).
            logger.debug(
                "No public key available for contributor %s — signature not verified",
                chunk.contributor_id[:16],
            )
            return True

        except Exception:
            logger.warning(
                "Signature verification failed for chunk %s from %s",
                chunk.hash[:16],
                chunk.contributor_id[:16],
            )
            return False

    # -----------------------------------------------------------------
    # Qdrant ingestion
    # -----------------------------------------------------------------

    async def ingest_chunk(self, chunk: Chunk) -> bool:
        """Verify, embed, and store a chunk in Qdrant.

        Steps:
            1. Check if the hash already exists in the collection.
            2. Generate an embedding via Ollama ``nomic-embed-text``.
            3. Upsert the point into Qdrant with full payload.

        Returns:
            ``True`` on success, ``False`` on failure.
        """
        if self._http_client is None:
            logger.error("HTTP client not initialized — cannot ingest chunk")
            return False

        try:
            # 1. Check for existing point by hash (scroll with filter)
            scroll_body: Dict[str, Any] = {
                "filter": {
                    "must": [
                        {"key": "hash", "match": {"value": chunk.hash}},
                    ]
                },
                "limit": 1,
                "with_payload": False,
                "with_vector": False,
            }
            scroll_resp = await self._http_client.post(
                f"{QDRANT_URL}/collections/{QDRANT_COLLECTION}/points/scroll",
                json=scroll_body,
            )
            if scroll_resp.status_code == 200:
                results = scroll_resp.json().get("result", {}).get("points", [])
                if results:
                    logger.debug("Chunk %s already in Qdrant — skipping", chunk.hash[:16])
                    self.chunk_store.put(chunk)
                    return True

            # 2. Generate embedding via Ollama
            embed_resp = await self._http_client.post(
                f"{OLLAMA_URL}/api/embed",
                json={"model": EMBEDDING_MODEL, "input": chunk.content},
            )
            if embed_resp.status_code != 200:
                logger.error(
                    "Ollama embedding failed (%d): %s",
                    embed_resp.status_code,
                    embed_resp.text[:200],
                )
                return False

            embed_data = embed_resp.json()
            embeddings = embed_data.get("embeddings")
            if not embeddings or not embeddings[0]:
                logger.error("Ollama returned empty embedding for chunk %s", chunk.hash[:16])
                return False
            vector: List[float] = embeddings[0]

            # 3. Upsert into Qdrant
            point_id = chunk.hash[:32]  # Use first 32 hex chars as a UUID-compatible ID
            # Convert to a valid UUID-like format for Qdrant
            point_uuid = (
                f"{point_id[:8]}-{point_id[8:12]}-{point_id[12:16]}"
                f"-{point_id[16:20]}-{point_id[20:32]}"
            )

            upsert_body: Dict[str, Any] = {
                "points": [
                    {
                        "id": point_uuid,
                        "vector": vector,
                        "payload": {
                            "hash": chunk.hash,
                            "content": chunk.content,
                            "contributor_id": chunk.contributor_id,
                            "timestamp": chunk.timestamp,
                            "visibility": chunk.visibility,
                            "layer": chunk.layer,
                            "source": "network",
                        },
                    }
                ]
            }
            upsert_resp = await self._http_client.put(
                f"{QDRANT_URL}/collections/{QDRANT_COLLECTION}/points",
                json=upsert_body,
            )
            if upsert_resp.status_code not in (200, 201):
                logger.error(
                    "Qdrant upsert failed (%d): %s",
                    upsert_resp.status_code,
                    upsert_resp.text[:200],
                )
                return False

            # Store locally
            self.chunk_store.put(chunk)
            logger.info("Chunk %s ingested into Qdrant successfully.", chunk.hash[:16])
            return True

        except httpx.ConnectError as exc:
            logger.error("Connection error during ingest: %s", exc)
            return False
        except Exception:
            logger.exception("Unexpected error ingesting chunk %s", chunk.hash[:16])
            return False

    # -----------------------------------------------------------------
    # Manifest
    # -----------------------------------------------------------------

    def get_local_manifest(self) -> List[str]:
        """Return the list of chunk hashes currently held in the local store."""
        return self.chunk_store.hashes()

    # -----------------------------------------------------------------
    # mDNS registration
    # -----------------------------------------------------------------

    def register_mdns(self) -> None:
        """Register this node's sync service via Zeroconf/mDNS.

        Broadcasts ``_superbrain._tcp.local.`` so other nodes on the LAN can
        discover us without manual IP configuration.
        """
        try:
            self._zeroconf = Zeroconf()

            # Resolve a usable LAN IP
            local_ip = self._get_local_ip()

            self._mdns_info = ServiceInfo(
                MDNS_SERVICE_TYPE,
                f"superbrain-{self.node_id[:8]}.{MDNS_SERVICE_TYPE}",
                addresses=[socket.inet_aton(local_ip)],
                port=self.port,
                properties={
                    "node_id": self.node_id,
                    "version": PROTOCOL_VERSION,
                },
            )
            self._zeroconf.register_service(self._mdns_info)

            # Start browsing for peers
            self._peer_listener = _PeerListener(self.node_id)
            self._browser = ServiceBrowser(
                self._zeroconf, MDNS_SERVICE_TYPE, self._peer_listener
            )

            logger.info("mDNS service registered on %s:%d", local_ip, self.port)

        except Exception:
            logger.exception("Failed to register mDNS service")

    def unregister_mdns(self) -> None:
        """Unregister and clean up Zeroconf resources."""
        try:
            if self._zeroconf is not None:
                if self._mdns_info is not None:
                    self._zeroconf.unregister_service(self._mdns_info)
                    logger.debug("mDNS service unregistered.")
                self._zeroconf.close()
                self._zeroconf = None
                self._mdns_info = None
                self._browser = None
                self._peer_listener = None
                logger.info("Zeroconf closed.")
        except Exception:
            logger.exception("Error unregistering mDNS service")

    # -----------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------

    @staticmethod
    def _parse_message(raw: str | bytes) -> Optional[Dict[str, Any]]:
        """Parse a raw WebSocket message as JSON.

        Returns ``None`` if the payload is not valid JSON or not a dict.
        """
        try:
            if isinstance(raw, bytes):
                raw = raw.decode("utf-8")
            data = json.loads(raw)
            if not isinstance(data, dict):
                return None
            return data
        except (json.JSONDecodeError, UnicodeDecodeError):
            return None

    @staticmethod
    async def _send_error(
        websocket: ServerConnection, code: str, message: str
    ) -> None:
        """Send an ERROR message to the peer."""
        payload: Dict[str, Any] = {
            "type": "error",
            "code": code,
            "message": message,
        }
        try:
            await websocket.send(json.dumps(payload))
        except websockets.exceptions.ConnectionClosed:
            pass

    @staticmethod
    def _get_local_ip() -> str:
        """Best-effort detection of the machine's LAN IP address."""
        try:
            # Connect to a non-routable address to determine the default interface
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
                s.connect(("10.255.255.255", 1))
                return s.getsockname()[0]
        except OSError:
            return "127.0.0.1"


# ---------------------------------------------------------------------------
# Convenience runner
# ---------------------------------------------------------------------------


def _generate_test_keys() -> tuple[Ed25519PrivateKey, str]:
    """Generate a fresh Ed25519 key pair and derive a node_id.

    Returns:
        (private_key, node_id) where node_id is the SHA-256 hex digest of the
        public key bytes (raw, 32-byte encoding).
    """
    private_key = Ed25519PrivateKey.generate()
    pub_bytes = private_key.public_key().public_bytes(
        Encoding.Raw, PublicFormat.Raw
    )
    node_id = hashlib.sha256(pub_bytes).hexdigest()
    return private_key, node_id


async def _run_server() -> None:
    """Entry-point coroutine: create a server with test keys and run it."""
    private_key, node_id = _generate_test_keys()
    store = ChunkStore()

    server = LANSyncServer(
        host=DEFAULT_HOST,
        port=DEFAULT_PORT,
        node_id=node_id,
        private_key=private_key,
        chunk_store=store,
    )

    loop = asyncio.get_running_loop()

    async def _shutdown(sig_name: str) -> None:
        logger.info("Received %s — initiating shutdown", sig_name)
        await server.stop()

    for sig in (signal.SIGINT, signal.SIGTERM):
        loop.add_signal_handler(
            sig,
            lambda s=sig: asyncio.ensure_future(_shutdown(s.name)),
        )

    logger.info("Node ID: %s", node_id)
    await server.start()


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
    )
    asyncio.run(_run_server())
